version: '3'

services:
  self-service-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge
