apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-service-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: self-service-portal
  template:
    metadata:
      labels:
        app: self-service-portal
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: cpu-pool
      containers:
      - name: self-service-portal
        image: europe-west4-docker.pkg.dev/mt-2dportal/self-service-portal/self-service-portal-img:latest
        imagePullPolicy: Always   
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 10   # Time to wait before the first probe
          periodSeconds: 10         # How often to perform the probe
          failureThreshold: 3       # Number of failures before marking the pod as unhealthy
          successThreshold: 1       # Number of successes required before marking the pod as healthy
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5    # Time to wait before the first readiness probe
          periodSeconds: 5          # How often to perform the readiness probe
          failureThreshold: 3       # Number of failures before marking the pod as not ready
          successThreshold: 1       # Number of successes required before marking the pod as ready
