name: Push to AWS ECR with ECR Cache

on:
  push:
    branches:
      - main_main

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::276696791566:role/github-actions-role
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region eu-west-2 | \
        docker login --username AWS --password-stdin 276696791566.dkr.ecr.eu-west-2.amazonaws.com

    - name: Build and Push Docker Image with ECR Cache
      run: |
        docker buildx build --no-cache --progress=plain \
          --cache-from=type=registry,ref=276696791566.dkr.ecr.eu-west-2.amazonaws.com/fastapi-s3:cache \
          --cache-to=type=registry,ref=276696791566.dkr.ecr.eu-west-2.amazonaws.com/fastapi-s3:cache,mode=max \
          --push -t 276696791566.dkr.ecr.eu-west-2.amazonaws.com/fastapi-s3:latest .


